Repository JuliaDiff/ChainRules.jl, pull requests merged in 2021-06, with the labels that each got.

#425 remove NanMath and SpecialFunctions.jl
  src/ChainRules.jl
  src/rulesets/packages/NaNMath.jl
  src/rulesets/packages/README.md
  src/rulesets/packages/SpecialFunctions.jl
  test/rulesets/packages/NaNMath.jl
  test/rulesets/packages/SpecialFunctions.jl
  test/runtests.jl
Labels: needs version bump

#424 do not reexport ChainRulesCore
  Project.toml
  src/ChainRules.jl
Labels: needs version bump

#427 Cancel previous running workflows
  .github/workflows/Cancel.yml
Labels: needs version bump

#429 stop CI testing every OS
  .github/workflows/CI.yml
  .github/workflows/JuliaNightly.yml
Labels: needs version bump

#440 fix `prod` tests on nightly
  test/rulesets/Base/mapreduce.jl
Labels: needs version bump, testing

#439 fix some numerical instabilities in Base tests
  Project.toml
  test/rulesets/Base/base.jl
  test/rulesets/Base/fastmath_able.jl
Labels: testing

#438 use `@maybe_inferred` instead of `@inferred`
  Project.toml
  test/rulesets/LinearAlgebra/factorization.jl
  test/rulesets/LinearAlgebra/matfun.jl
  test/rulesets/LinearAlgebra/symmetric.jl
Labels: needs version bump, testing

#445 fix #379: numeric instabilities in eigen tests
  Project.toml
  test/rulesets/LinearAlgebra/factorization.jl
  test/runtests.jl
Labels: testing

#454 handle 1 arg matrix cholesky
  src/rulesets/LinearAlgebra/factorization.jl
  test/rulesets/LinearAlgebra/factorization.jl
Labels: needs version bump
